# The Basics of NumPy Arrays

## Numpy Array Attributes

In [1]:
import numpy as np
np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10, size=6) # one dimensional array
x2 = np.random.randint(10, size=(3, 4)) # two dimensional array
x3 = np.random.randint(10, size=(3,4,5)) # three dimensional array

# NB ndim => nunmber of dimensions, shape => size of each dimension and size => total size of array

In [5]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [7]:
print("x3 dtype:", x3.dtype)
print("x3 itemsize", x3.itemsize, "bytes")
print("x3 nbytes:", x3.nbytes, "bytes")

# in general we expect that nbytes = itemsize * size

x3 dtype: int64
x3 itemsize 8 bytes
x3 nbytes: 480 bytes


In [9]:
# in a multi dimensional array, items can be accessed using a comma separated tuple of indeces
print(x2)
print(x2[0, 0])
print(x2[1, 1])
print(x2[2, -1])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3
6
7


In [13]:
# values can also be modified using this notation
x2[0, 0] = 12
print(x2[0, 0])

12


In [14]:
# bear in mind that np arrays can only contain a single type, inserting a floting point leads to it being truncated
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

##  Array Slicing

In [15]:
# python => x[start:stop:step] (defualt: start=0, stop=size, step = 1)
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
print(x[5:]) # elements after index 5
print(x[4:7]) # middle sub-array
print(x[::2]) # every other element
print(x[1::2]) # every other elements, starting at 1
print(x[::-1]) # every element reversed
print(x[5::-2]) # every other element reversed from 5

[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


## Multi Demensinal subarrays

In [19]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [20]:
x2[:2, :3] # 2 rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [21]:
x2[:3, ::2] # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [22]:
x2[::-1, ::-1] # reverse all sub arrays

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

## Accessing array rows and columns

In [25]:
print(x2[:, 0]) # first column of x2

[12  7  1]


In [27]:
print(x2[0, :]) # first row of x2
print(x2[0]) # first row of x2

[12  5  2  4]
[12  5  2  4]


In [29]:
# NB array slicing returns a view of the array rather than a copy,
# modifying a sliced array will also modify the original
x2_sub = x2[:2, :2]
x2_sub[0, 0] = 99
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Copying an Array

In [32]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy[0, 0] = 42 # modifying a cope wont change the original array
print(x2_sub_copy)
print(x2)

[[42  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reshaping an Array

In [37]:
grid = np.arange(1, 10)
print(grid)
grid_reshaped = grid.reshape((3,3))
print(grid_reshaped)
# Note that for this to work, the size of the initial array must match the size of the reshaped array.

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
x = np.array([1, 2, 3])
print(x)

# row vector via reshape
print(x.reshape((1, 3)))

[1 2 3]
[[1 2 3]]


In [42]:
# row vector via new axis
x[np.newaxis, :]

array([[1, 2, 3]])

In [43]:
# column vector via reshape
x.reshape(3, 1)

array([[1],
       [2],
       [3]])

In [44]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting

In [45]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [46]:
# concatenate more than two arrays at once
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [52]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
# concatenate along the first axis
np.concatenate([grid, grid], axis = 0) # axis argument is 0 by default, so optional here

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [53]:
# concatenate along the second axis (zero indexed)
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])