## Creating Arrays from Python Lists

In [1]:
import numpy as np

In [2]:
# numpy arrays contain only a single type of data
np.array([1, 2, 3, 5, 3])

array([1, 2, 3, 5, 3])

In [3]:
# if data types are mixed, numpy will upcast if possible
# here integers are cast to floats

np.array([3.14, 2, 3, 6])

array([3.14, 2.  , 3.  , 6.  ])

In [4]:
# if we want to explicitly set the data type of the resulting array, we can use dtype keyword
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [5]:
# numpy arrays can explicitly be multi dimensional
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch

In [6]:
# Create an array of len 10 filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# Create a 3x5 floating point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# this is similar to the range() function
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
# Create a 3x3 array of uniformly distributed random values
# with mean 0 and standard deviation 1
np.random.random((3, 3))

array([[0.23733782, 0.95145055, 0.97262455],
       [0.09953145, 0.81362973, 0.88108161],
       [0.20409693, 0.65779162, 0.18518013]])

In [14]:
# create a 3x3 array of random integers in the interval [0, 10]
np.random.randint(0, 10, (3, 3))

array([[1, 3, 1],
       [0, 3, 5],
       [7, 0, 7]])

In [16]:
# Create a 3x3 identity matrix
# Identity Matrix => a square matrix in which all the elements of the principal diagonal are ones
# and all other elements are zeros.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])